version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy:alpine-0.7.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /etc/localtime/:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./share:/usr/share/nginx/html
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.8.1
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx

# docker network create web
networks:
  web:
    external: true
